version: '3.8'

services:
  database:
    restart: always
    image: postgres
    environment:
      - POSTGRES_DB=${PG_DATABASE}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: bash -c "sleep 2; echo 'Database is ready, running migrations...'; python3 manage.py migrate; sleep 2; echo 'Starting the server...'; python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      database:
        condition: service_healthy